### ISSUE TITLE
Bot is not working 

### ISSUE THREAD

**Issue by Blackbooster372** [uzox/uzox#15]
It showing mongoose connected 
But bot not working

**Comment by Moquent** [comment]
what is your config

**Comment by Blackbooster372** [comment]
> what is your config

{
    "TOKEN": "mytoken",
    "NAME": "music",
    "DEFAULT_PREFIX": "_",
    "MONGODB_URI": "mongodb+srv://.............my mongo url",
    "MICROSERVICES_API": "https://uzox.xyz/api/",
    "SPOTIFY_API_CONFIG": {
        "clientId": "d68c4f87f81e47ac******76e4e29770",
        "clientSecret": "15d130b3d8084****19cfea480553c88",
        "redirectUri": ""
    },
    "LAVALINK_SERVERS": [
        {
            "name": "OGGY#9889",
            "url": "ssl.freelavalink.ga:443",
            "auth": "www.freelavalink.ga",
            "secure":true
        }
    ]
}

**Comment by Blackbooster372** [comment]
![Uploading IMG_20221219_081515.jpg…]()

**Comment by Blackbooster372** [comment]
![Uploading IMG_20221219_081515.jpg…]()

**Comment by Blackbooster372** [comment]
> uzox@3.0.0 start

> NODE_ENV=production node .

[Mon Dec 19 2022 02:41:29] Launched shard 0

Mongoose connected

/home/runner/uzox/node_modules/discord.js /src/sharding/Shard.js:167 reject(new DiscordjsError(ErrorCo des.ShardingReadyTimeout, this.id));

Error [ShardingReadyTimeout]: Shard 0's C lient took too long to become ready. at Timeout.onTimeout (/home/runner/uz ox/node_modules/discord.js/src/sharding/S

hard.js:167:16)

s:559:17)

at listOnTimeout (node:internal/timer at processTimers (node: internal/timer

s:502:7) { code: 'ShardingReadyTimeout'

}

**Comment by Moquent** [comment]
oh it's a timeout, make sure you have a good internet connection.
